### ISSUE TITLE
Doesn't work for local files

### ISSUE THREAD

**Issue by wbt** [excitedleigh/newtab#2]
When the homepage is set to a file:// URL, opening a new tab causes the "loading" circles to be going in the tab part and after a moment, the following error is displayed:

>Hmm. We’re having trouble finding that site.
>We can’t connect to the server at file.
>If that address is correct, here are three other things you can try:
>   Try again later.
    Check your network connection.
    If you are connected but behind a firewall, check that Firefox has permission to access the Web.

Clicking the "home" button loads the page correctly, so it's not that the file is inaccessible.

The much more popular competing add-on has a [similar issue](https://github.com/benbasson/newtabhomepage/issues/24).

**Comment by daisylb** [comment]
Hi, thanks for reporting this issue!

Unfortunately it looks like this is not possible due to the same reasons as discussed in that thread, in particular this comment: https://github.com/benbasson/newtabhomepage/issues/24#issuecomment-347371090

It's possible, but not guaranteed, that when [support for `<iframe mozbrowser>` is added to WebExtensions](https://bugzilla.mozilla.org/show_bug.cgi?id=1318532) this will be possible, but as noted in that bug report, that feature is currently on hold anyway.

I'm going to close this, but if a workaround becomes apparent I'm happy for it to be reopened.
